name: Prepare dotnet dependencies
description: Installs the dotnet CLI and restores packages
inputs:
  dependency-config-path:
    required: true
    type: string
  dotnet-version:
    required: false
    type: string
    default: '9.0.x'

runs:
  using: composite
  steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Cache dependencies
      id: cache_deps
      uses: actions/cache@v4
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os}}-nuget-${{ hashFiles(inputs.dependency-config-path) }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Restore dependencies
      if: steps.cache_deps.outputs.cache-hit != 'true'
      shell: bash
      run: dotnet restore
