name: Create beta release

on:
  push:
    branches:
      - develop
    tags:
      - v**

jobs:
  create-full-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Pack Release
        id: pack-release
        uses: ./.github/workflows/_pack-release.yml