name: create-release

on:
  push:
    branches: [ "main", "develop" ]

jobs:
  create-version:
    if: ${{ ! startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
  
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v3
      with:
        versionSpec: '6.3.x'

    - name: Determine Version
      id: version_step
      uses: gittools/actions/gitversion/execute@v3
      with:
        useConfigFile: true
        updateProjectFiles: true

    - name: Tag Release
      run: |
        git commit -a -m "Create release ${{ steps.version_step.outputs.MajorMinorPatch }}"
        git tag v${{ steps.version_step.outputs.MajorMinorPatch }}
        git push origin --tags
    